version: '2'
services:
    datacenter-app:
        image: t08094a/alarmdisplay-datacenter
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mariadb://datacenter-mariadb:3306/datacenter
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 9001:8080
    datacenter-mariadb:
        extends:
            file: mariadb.yml
            service: datacenter-mariadb
