version: '3'
services:
    datacenter-app:
        image: t08094a/alarmdisplay-datacenter:latest
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=dataCenter
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=kafka
            - SPRING_CLOUD_STREAM_KAFKA_BINDER_ZK_NODES=zookeeper
        ports:
            - "9000:8080"
        networks:
            - network_backend
            - network_frontend
        deploy:
            placement:
                constraints: [node.role == manager]
            restart_policy:
                condition: on-failure

    mongodb:
        image: mongo:3.4.10
        ports:
            - "27017:27017"
        volumes:
            - db_volume:/data/db/
        networks:
            - network_backend
        deploy:
            placement:
                constraints: [node.role == manager]
            restart_policy:
                condition: on-failure


    zookeeper:
        image: wurstmeister/zookeeper:3.4.6
        ports:
          - "2181:2181"
        networks:
            - network_backend

    kafka:
        image: wurstmeister/kafka:1.0.0
        environment:
            #KAFKA_ADVERTISED_HOST_NAME: localhost
            KAFKA_ADVERTISED_HOST_NAME: kafka
            KAFKA_ADVERTISED_PORT: 9092
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_CREATE_TOPICS: "topic-jhipster:1:1"
        ports:
            - "9092:9092"
        networks:
            - network_backend
            - network_frontend

volumes:
    db_volume:

networks:
  network_backend:
  network_frontend:
