version: '3'
services:
    datacenter-mongodb:
        image: mongo:3.4.10
        ports:
            - "27017:27017"
        volumes:
            - data-volume:/data/db/
        deploy:
            placement:
                constraints: [node.role == manager]
            restart_policy:
                condition: on-failure

volumes:
    data-volume:
