version: '3'
services:
    swagger-editor:
        image: swaggerapi/swagger-editor:latest
        ports:
            - "7742:8080"
        deploy:
            restart_policy:
                condition: on-failure
