version: "2"
services:
    datacenter-app:
        image: t08094a/alarmdisplay-datacenter
        container_name: datacenter-app
        # user: "node"
        restart: unless-stopped
        ports:
            - "9001:3000"
        environment:
            - START_SLEEP=10 # gives time for the database to boot before the application
            #- MONGO_URL=mongodb://datacenter-mongodb/alarmdisplay-datacenter
        depends_on:
            - datacenter-mongodb

    datacenter-mongodb:
        extends:
            file: mongo.yml
            service: datacenter-mongodb
        restart: unless-stopped
        volumes:
            - datacenter-mongodb_volume:/data/db/

    datacenter-rabbitmq:
        extends:
            file: rabbitmq.yml
            service: datacenter-rabbitmq
        restart: unless-stopped

    # datacenter-mongo-express:
    #     extends:
    #         file: mongoexpress.yml
    #         service: datacenter-mongo-express
    #     # environment:
    #     ports:
    #         - "9002:8081"

volumes:
    datacenter-mongodb_volume:
